version: '2'

services:
    nginx:
        build: nginx
        volumes:
            - "./logs/nginx/:/var/log/nginx"
            - "../../front-end/app:/var/www/"
        environment:
            VIRTUAL_HOST: iot_lora.lan.iict.ch
            LETSENCRYPT_HOST: iot_lora.lan.iict.ch
            LETSENCRYPT_EMAIL: ali.muladi@heig-vd.ch
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/vhost.d:/etc/nginx/vhost.d"
            - "./nginx/html:/usr/share/nginx/html"
            - "./nginx/certs:/etc/nginx/certs"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        volumes_from:
            - "nginx-proxy"


